#!/bin/bash

echo "🔍 Verificando domínios autorizados no Firebase..."
echo ""
echo "📋 Instruções:"
echo ""
echo "1. Acesse: https://console.firebase.google.com/project/chs-crono-capilar-2026/authentication/settings"
echo ""
echo "2. Role até a seção 'Authorized domains'"
echo ""
echo "3. Verifique se estes domínios estão na lista:"
echo "   ✅ cronocapilar.inoveai.app.br"
echo "   ✅ chs-crono-capilar-2026.firebaseapp.com"
echo "   ✅ localhost (para desenvolvimento)"
echo ""
echo "4. Se 'cronocapilar.inoveai.app.br' NÃO estiver:"
echo "   - Clique em 'Add domain'"
echo "   - Digite: cronocapilar.inoveai.app.br"
echo "   - Clique em 'Add'"
echo ""
echo "5. Aguarde 1-2 minutos e teste novamente"
echo ""
